debezium.server.name=debezium

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=60000
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgres
debezium.source.database.dbname=users
# debezium.source.schema.include.list=public
debezium.source.table.include.list=public.events
debezium.source.plugin.name=pgoutput
debezium.source.topic.prefix=cdc

debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=debezium
debezium.sink.rabbitmq.connection.password=debezium
debezium.sink.rabbitmq.connection.virtual.host=cdc
debezium.sink.rabbitmq.exchange=cdc
debezium.sink.rabbitmq.routingKeyFromTopicName=true
